---
- name: Install apt prerequisites
  apt:
    name: "{{item}}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip

# Required for docker_swarm_info
- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present

- name: Import Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present

- name: Install Docker
  apt:
    name: "{{item}}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io