---
- name: Setup graylog_stack_mongo_root_password secret
  docker_secret:
    name: graylog_stack_mongo_root_password
    data: "{{graylog_stack_mongo_root_password}}"

- name: Setup graylog_stack_mongod_keyfile secret
  docker_secret:
    name: graylog_stack_mongod_keyfile
    data: "{{graylog_stack_mongod_keyfile}}"
