---
# group_vars example:
# graylog_stack_mongod_nodes:
#  docker_service: docker_hostname

- name: Tag Docker nodes
  docker_node:
    hostname: "{{item.value}}"
    labels:
      graylog_cluster_mongodb_role: "{{item.key}}"
  loop: "{{graylog_stack_mongod_nodes|dict2items}}"